---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_os_family != 'FreeBSD'

- name: Restart retry-endpoint
  ansible.builtin.service:
    name: "{{ 'retry-endpoint' if ansible_os_family != 'FreeBSD' else 'retry_endpoint' }}"
    state: restarted
