---
- name: Deploy Redis cache node
  hosts: redis_nodes
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: [common]

    - role: redis
      tags: [redis]

- name: Deploy retry-endpoint nodes
  hosts: retry_endpoint_nodes
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: [common]

    - role: perf-tuning
      tags: [perf-tuning]

    - role: retry-endpoint
      tags: [retry_endpoint]

    - role: networking
      tags: [networking]

    - role: firewall
      tags: [firewall]
      when: enable_firewall | bool
